resolver: lts-8.9

packages:
- '.'
- location:
    git: https://github.com/clash-lang/ghc-typelits-natnormalise.git
    commit: f81d6841edd6baea23dbe0ff9a896571d0e72d09
  extra-dep: true


flags:
  ghc-typelits-knownnat:
    deverror: true
